version: '3.8'

services:
  web:
    image: python:3.9-slim
    container_name: django-postgres-backend_app
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=projetoMariaAlvez.settings
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=centro_de_bem_estar_maria_alvez
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=UserPassword@2024
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: UserPassword@2024
      POSTGRES_DB: centro_de_bem_estar_maria_alvez
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
