version: "3.8"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: UserPassword@2024
      POSTGRES_DB: centro_de_bem_estar_maria_alvez
    volumes:
      - ./init_dump.sql:/docker-entrypoint-initdb.d/init_dump.sql

    ports:
      - "5432:5432"

  web:
    image: python:3.9-slim
    container_name: django-postgres-backend_app
    build:
      context: .
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=projetoMariaAlvez.settings
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=centro_de_bem_estar_maria_alvez
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "8000:8000"

volumes:
  postgres_data:
