services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy  # Garante que o postgres esteja saudável
    environment:
      - DB_HOST=postgres
      - DB_NAME=centro_de_bem_estar_maria_alvez
      - DB_USER=admin
      - DB_PASSWORD=adminadmin
      - DB_PORT=5432

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: centro_de_bem_estar_maria_alvez
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${PWD}/backend/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d centro_de_bem_estar_maria_alvez"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB"]

networks:
  default:
    driver: bridge