version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Diretório onde está o Dockerfile do backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app  # Monta o diretório backend no container
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do backend
    depends_on:
      - db  # Aguarda o banco de dados ser iniciado

  db:
    image: postgres:13  # Utiliza a imagem do PostgreSQL
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - ./data/db:/var/lib/postgresql/data  # Persistência dos dados
    ports:
      - "5432:5432"  # Porta do banco de dados