services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=clinica_vet
      - POSTGRES_USER=vet_user
      - POSTGRES_PASSWORD=vet_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:5432 --timeout=30 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py create_admin &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=postgresql://vet_user:vet_password@db:5432/clinica_vet
    depends_on:
      - db

volumes:
  postgres_data: