# Generated by Django 3.2.25 on 2025-02-21 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetoMariaAlvezApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Prestadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('sobrenome', models.CharField(max_length=80)),
                ('rua', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='id',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='administracao',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Injetável', 'Injetável'), ('Tópico', 'Tópico')], default='Oral', max_length=50),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='contraindicacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 21, 14, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dose',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='estoque',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fabricante',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_medicamento',
            field=models.BigAutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='indicacao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='principio_ativo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id_vacina', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('dose', models.CharField(max_length=50)),
                ('intervalo', models.IntegerField(help_text='Intervalo em meses')),
                ('fabricante', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recomendacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoMariaAlvezApp.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id_raca', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoMariaAlvezApp.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Imagem', 'Imagem'), ('Laboratorial', 'Laboratorial'), ('Clínico', 'Clínico')], max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('duracao', models.DurationField(help_text='Duração média do exame (hh:mm:ss)')),
                ('recomendacoes_pre', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoMariaAlvezApp.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoMariaAlvezApp.especie')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoMariaAlvezApp.raca')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoMariaAlvezApp.tutor')),
            ],
        ),
    ]
