# Generated by Django 3.2.25 on 2025-02-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoMariaAlvezApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='animalcastracao',
            options={'verbose_name': 'Animal para Castração', 'verbose_name_plural': 'Animais para Castração'},
        ),
        migrations.AlterModelOptions(
            name='cirurgia',
            options={'verbose_name': 'Cirurgia', 'verbose_name_plural': 'Cirurgias'},
        ),
        migrations.AlterModelOptions(
            name='consultaclinica',
            options={'verbose_name': 'Consulta Clínica', 'verbose_name_plural': 'Consultas Clínicas'},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterModelOptions(
            name='exame',
            options={'verbose_name': 'Exame', 'verbose_name_plural': 'Exames'},
        ),
        migrations.AlterModelOptions(
            name='exameveterinario',
            options={'verbose_name': 'Exame Veterinário', 'verbose_name_plural': 'Exames Veterinários'},
        ),
        migrations.AlterModelOptions(
            name='internacao',
            options={'verbose_name': 'Internação', 'verbose_name_plural': 'Internações'},
        ),
        migrations.AlterModelOptions(
            name='listacastracao',
            options={'verbose_name': 'Lista de Castração', 'verbose_name_plural': 'Listas de Castração'},
        ),
        migrations.AlterModelOptions(
            name='listaexames',
            options={'verbose_name': 'Lista de Exames', 'verbose_name_plural': 'Listas de Exames'},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='prestadores',
            options={'verbose_name': 'Prestador', 'verbose_name_plural': 'Prestadores'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'verbose_name': 'Raça', 'verbose_name_plural': 'Raças'},
        ),
        migrations.AlterModelOptions(
            name='relatorioacompanhamento',
            options={'verbose_name': 'Relatório de Acompanhamento', 'verbose_name_plural': 'Relatórios de Acompanhamento'},
        ),
        migrations.AlterModelOptions(
            name='relatorioatendimento',
            options={'verbose_name': 'Relatório de Atendimento', 'verbose_name_plural': 'Relatórios de Atendimento'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AlterModelOptions(
            name='vacina',
            options={'verbose_name': 'Vacina', 'verbose_name_plural': 'Vacinas'},
        ),
        migrations.AlterModelOptions(
            name='vacinavermifugos',
            options={'verbose_name': 'Vacina/Vermífugo', 'verbose_name_plural': 'Vacinas/Vermífugos'},
        ),
    ]
