# Generated by Django 3.2.25 on 2025-03-01 04:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetoMariaAlvezApp', '0002_auto_20250228_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data em que o tutor foi cadastrado', verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='consultaclinica',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Consulta'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bairro',
            field=models.CharField(max_length=80, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'Digite um CEP válido no formato 12345-678.')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cidade',
            field=models.CharField(max_length=80, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'Digite um CPF válido no formato 123.456.789-00')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id_tutor',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID do Tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rua',
            field=models.CharField(max_length=80, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='sobrenome',
            field=models.CharField(max_length=80, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Digite um número de telefone válido.')], verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['cpf'], name='tutor_cpf_idx'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['nome', 'sobrenome'], name='tutor_nome_idx'),
        ),
    ]
