# Generated by Django 3.2.25 on 2025-02-21 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetoMariaAlvezApp', '0002_auto_20250221_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
