# Generated by Django 3.2.25 on 2025-03-01 05:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetoMariaAlvezApp', '0003_auto_20250301_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data em que o animal foi cadastrado', verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='projetoMariaAlvezApp.especie', verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_animal',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID do Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'A idade deve ser maior ou igual a 0')], verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(help_text='Nome do animal (máximo 80 caracteres)', max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='projetoMariaAlvezApp.raca', verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='projetoMariaAlvezApp.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='relatorioacompanhamento',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?55?\\d{10,11}$', 'Digite um número de telefone válido.')], verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['nome'], name='animal_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['tutor'], name='animal_tutor_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['especie'], name='animal_especie_idx'),
        ),
    ]
