# Generated by Django 3.2.25 on 2025-03-01 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoMariaAlvezApp', '0004_auto_20250301_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}[-.\\s]?\\d{3}$', 'Digite um CEP válido no formato: 12345-678, 12345678, ou 12345 678.')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$|\\d{11}$', 'Digite um CPF válido no formato: 123.456.789-00 ou 01234567890 (11 dígitos). O CPF será armazenado como 01234567890 (somente dígitos).')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?55?\\s?(\\(?\\d{2}\\)?\\s?)?\\d{8,9}|\\d{10,11}$', 'Digite um número de telefone válido no formato: +55 (DD) XXXX-XXXX, (DD) XXXX-XXXX, DDDXXXXXXXX, ou XXXXXXXXXXX (10 ou 11 dígitos). O número será armazenado como DDDXXXXXXXX (somente dígitos, sem +55).')], verbose_name='Telefone'),
        ),
    ]
