# Generated by Django 3.2.25 on 2025-05-18 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoMariaAlvezApp', '0005_auto_20250301_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['nome', 'sobrenome'], 'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='animalcastracao',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='numero',
        ),
        migrations.AddField(
            model_name='tutor',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o cadastro do tutor está ativo', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'Digite um CEP válido no formato: XXXXX-XXX, como 12345-678')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s9\\d{4}-\\d{4}$', 'Digite um telefone válido no formato: (XX) 9XXXX-XXXX, como (11) 91234-5678')], verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='tutor',
            index=models.Index(fields=['email'], name='tutor_email_idx'),
        ),
    ]
